version: '3.9'
services:

  main:
    container_name: sshTunnel-dev
    restart: unless-stopped
    network_mode: host
    build:
      context: src
    environment:
      remoteHost: ${vpsHost:?}
      remoteUser: ${vpsUser:?}
      httpLocal: 80
      httpRemote: 20080
      qbitLocal: 3069
      qbitRemote: 23069
    volumes:
      - type: bind
        source: ${vpsIdentity:?}
        target: /app/identity
        read_only: true
