name: pushDocker
on:
  push:
    branches:
      - main
  schedule:
    - cron: 45 23 * * 0 # https://crontab.guru/#45_23_*_*_0
  repository_dispatch:
    types: [bumped]
jobs:
  debug:
    uses: jaid/workflows/.github/workflows/debug.yml@main
  job:
    name: ${{ github.workflow }}
    uses: jaid/workflows/.github/workflows/pushDocker.yml@main
    permissions:
      contents: read
      packages: write
    with:
      dockerHubUser: jaidchen
      matrixPlatform: linux/amd64 linux/arm64/v8
      matrixAdditionEvals: |-
        builderImage: `jaidchen/builder:6.0.0${platform === `linux/arm64/v8` ? `-arm8` : ``}`
        runnerImage: `jaidchen/runner:5.1.0${platform === `linux/arm64/v8` ? `-arm8` : ``}`
      testAppArgs: bash -c 'ls --all -l'
      testEval: status === 0 && stdout.length > 0
      versionTag: ${{ github.event.client_payload.newTag }}
    secrets:
      dockerHubToken: ${{ secrets.dockerHubToken }}
